### ISSUE TITLE
Unreal _Toolkit : Creation of sample script/Demo of live mesh push/update

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Unreal_Toolkit#20]
See https://github.com/BHoM/Unreal_Toolkit/issues/5
In addition to above - and simple test file. Creation of a demo model.

**Comment by alelom** [comment]
Example files can be found in `\\srv-lax03\Non-Project\BHLA Comp Collective Dev\Research and Development\VR\VR_Toolkit\Output\190501 VR Toolkit`

I'll move them in Sharepoint and post the link here, as the server there proves way too slow.

**Comment by alelom** [comment]
Sample file can be found here:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Unreal_Toolkit/190501%20VR%20Toolkit?csf=1&e=YOhB4M
