### ISSUE TITLE
Unreal_Toolkit: plan/agree on VR mesh&material implementation in BHoM

### ISSUE THREAD

**Issue by alelom** [BHoM/Unreal_Toolkit#25]
Aim: VR mesh&material implementation to be agreed between BH & Heatherwick contributors (all Unreal_Toolkit contributors).

Once #24 is clear, options could be: 
1. The material information could be encoded as JSON message with the rest of the mesh.
2. The mesh could be pushed separately from the material. For example, the mesh could be saved as an .fbx file with a reference to the material. **Export time should be evaluated** - Socket VS Save to file.
3. Any other idea

**Comment by enarhi** [comment]
Closing, `RenderMesh` is our implemented solution for the above and future development should work with them accordingly.
