### ISSUE TITLE
Unreal_Toolkit: plan how to receive/implement VR material on Blueprint

### ISSUE THREAD

**Issue by alelom** [BHoM/Unreal_Toolkit#26]
Once #25 is clarified, plan how to implement the Unreal side of the VR material.

Material should be received and applied automatically to meshes/assets referencing it.

Discuss the options:  
- Meshes could come automatically with a material attached (assigned to them when created through the existing Blueprint script).
- Meshes could reference to a material name which is then linked through Blueprint.
- Any other idea

**Comment by enarhi** [comment]
Closing, `RenderMesh` is our implemented solution for the above and future development should work with them accordingly.
