### ISSUE TITLE
Unreal_Toolkit: implement VR material in Unreal

### ISSUE THREAD

**Issue by alelom** [BHoM/Unreal_Toolkit#28]
Implement the Unreal side of the mesh material.

Depending on the path chosen in #27, one or more of the following tasks will be needed:

- Create Blueprint logic to automate the mesh material assignment upon receipt.
- If we go for the "save to file" option (see #25), this might require a logic to be implemented in Blueprint that should read the file and assign the materials to the mesh.
- If we go for the Socket option (see #25), this might require modification of the unreal socket receiver C++ code to allow for proper material transmission. Hopefully this should not be needed.

**Comment by enarhi** [comment]
Closing, `RenderMesh` is our implemented solution for the above and future development should work with them accordingly.
